"""crear tabla categorias

Revision ID: 9a974154a336
Revises: 
Create Date: 2026-09-15 05:52:54.132576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a974154a336'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    # ### end Alembic commands ###

    # --- Carga de las 8 categorías iniciales de VIVÍ SMA ---
    categorias_table = sa.table(
        "categorias",
        sa.column("nombre", sa.String),
        sa.column("descripcion", sa.String),
    )
    op.bulk_insert(
        categorias_table,
        [
            {
                "nombre": "Gastronomía",
                "descripcion": "Restaurantes, cafés, cervecerías, pizzerías, hamburgueserías, tapiocas, crepes y delivery.",
            },
            {
                "nombre": "Alojamiento",
                "descripcion": "Hoteles, cabañas, departamentos, dormis y camping.",
            },
            {
                "nombre": "Turismo",
                "descripcion": "Excursiones, trekking, pesca y cabalgatas.",
            },
            {
                "nombre": "Comercios",
                "descripcion": "Ropa, artesanías, productos regionales, kioscos, supermercados, almacenes, ferreterías, imprentas y más.",
            },
            {
                "nombre": "Servicios",
                "descripcion": "Electricistas, plomeros, mecánicos y más.",
            },
            {
                "nombre": "Salud y bienestar",
                "descripcion": "Farmacias, gimnasios, hospitales, centros de salud y más.",
            },
            {
                "nombre": "Transporte",
                "descripcion": "Taxis, alquiler de vehículos, colectivos y más.",
            },
            {
                "nombre": "Eventos",
                "descripcion": "Shows, ferias, teatros, actividades locales y más.",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
